spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  #禁用缓存+ctrl+f9页面重新编译 实时生效
  thymeleaf:
    cache: false
server:
  port: 80
pageNumber: 8

